publish_to: "none" # Prevents publishing to pub.dev

name: global365_widgets
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0



# hussain_widgets:
# git:
# url: git@github.com:hussainhabib2/hussain_widgets.git
# ref: main #branch name of private git repo