publish_to: "none" # Prevents publishing to pub.dev

name: global365_widgets
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg:
  intl: ^0.20.2
  delightful_toast: ^1.1.0
  vph_common_widgets: ^0.0.3
  dropdown_button2:
  bootstrap_icons:
  loader_overlay:
  scroll_to_index:
  dotted_border: ^2.1.0
  url_launcher:
  dio: ^5.4.1
  go_router: ^14.6.2
  flutter_spinkit: ^5.0.0
  flutter_inappwebview: ^6.1.5
  webviewx_plus: ^0.5.0




dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/svg/



# hussain_widgets:
# git:
# url: git@github.com:hussainhabib2/hussain_widgets.git
# ref: main #branch name of private git repo